// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.spt.priceofriceservice.domain;

import com.spt.priceofriceservice.domain.SeedRice;
import com.spt.priceofriceservice.domain.SeedRiceDataOnDemand;
import com.spt.priceofriceservice.domain.SeedRiceIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SeedRiceIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SeedRiceIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SeedRiceIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SeedRiceIntegrationTest: @Transactional;
    
    @Autowired
    SeedRiceDataOnDemand SeedRiceIntegrationTest.dod;
    
    @Test
    public void SeedRiceIntegrationTest.testCountSeedRices() {
        Assert.assertNotNull("Data on demand for 'SeedRice' failed to initialize correctly", dod.getRandomSeedRice());
        long count = SeedRice.countSeedRices();
        Assert.assertTrue("Counter for 'SeedRice' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SeedRiceIntegrationTest.testFindSeedRice() {
        SeedRice obj = dod.getRandomSeedRice();
        Assert.assertNotNull("Data on demand for 'SeedRice' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SeedRice' failed to provide an identifier", id);
        obj = SeedRice.findSeedRice(id);
        Assert.assertNotNull("Find method for 'SeedRice' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SeedRice' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SeedRiceIntegrationTest.testFindAllSeedRices() {
        Assert.assertNotNull("Data on demand for 'SeedRice' failed to initialize correctly", dod.getRandomSeedRice());
        long count = SeedRice.countSeedRices();
        Assert.assertTrue("Too expensive to perform a find all test for 'SeedRice', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SeedRice> result = SeedRice.findAllSeedRices();
        Assert.assertNotNull("Find all method for 'SeedRice' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SeedRice' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SeedRiceIntegrationTest.testFindSeedRiceEntries() {
        Assert.assertNotNull("Data on demand for 'SeedRice' failed to initialize correctly", dod.getRandomSeedRice());
        long count = SeedRice.countSeedRices();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SeedRice> result = SeedRice.findSeedRiceEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SeedRice' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SeedRice' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SeedRiceIntegrationTest.testFlush() {
        SeedRice obj = dod.getRandomSeedRice();
        Assert.assertNotNull("Data on demand for 'SeedRice' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SeedRice' failed to provide an identifier", id);
        obj = SeedRice.findSeedRice(id);
        Assert.assertNotNull("Find method for 'SeedRice' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySeedRice(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'SeedRice' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SeedRiceIntegrationTest.testMergeUpdate() {
        SeedRice obj = dod.getRandomSeedRice();
        Assert.assertNotNull("Data on demand for 'SeedRice' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SeedRice' failed to provide an identifier", id);
        obj = SeedRice.findSeedRice(id);
        boolean modified =  dod.modifySeedRice(obj);
        Integer currentVersion = obj.getVersion();
        SeedRice merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'SeedRice' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SeedRiceIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SeedRice' failed to initialize correctly", dod.getRandomSeedRice());
        SeedRice obj = dod.getNewTransientSeedRice(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SeedRice' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SeedRice' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'SeedRice' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SeedRiceIntegrationTest.testRemove() {
        SeedRice obj = dod.getRandomSeedRice();
        Assert.assertNotNull("Data on demand for 'SeedRice' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SeedRice' failed to provide an identifier", id);
        obj = SeedRice.findSeedRice(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SeedRice' with identifier '" + id + "'", SeedRice.findSeedRice(id));
    }
    
}
