// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.spt.priceofriceservice.domain;

import com.spt.priceofriceservice.domain.SeedRice;
import com.spt.priceofriceservice.domain.SeedRiceDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect SeedRiceDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SeedRiceDataOnDemand: @Component;
    
    private Random SeedRiceDataOnDemand.rnd = new SecureRandom();
    
    private List<SeedRice> SeedRiceDataOnDemand.data;
    
    public SeedRice SeedRiceDataOnDemand.getNewTransientSeedRice(int index) {
        SeedRice obj = new SeedRice();
        setSeedRiceCode(obj, index);
        setSeedRiceName(obj, index);
        return obj;
    }
    
    public void SeedRiceDataOnDemand.setSeedRiceCode(SeedRice obj, int index) {
        String seedRiceCode = "seedRiceCode_" + index;
        obj.setSeedRiceCode(seedRiceCode);
    }
    
    public void SeedRiceDataOnDemand.setSeedRiceName(SeedRice obj, int index) {
        String seedRiceName = "seedRiceName_" + index;
        obj.setSeedRiceName(seedRiceName);
    }
    
    public SeedRice SeedRiceDataOnDemand.getSpecificSeedRice(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SeedRice obj = data.get(index);
        Long id = obj.getId();
        return SeedRice.findSeedRice(id);
    }
    
    public SeedRice SeedRiceDataOnDemand.getRandomSeedRice() {
        init();
        SeedRice obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return SeedRice.findSeedRice(id);
    }
    
    public boolean SeedRiceDataOnDemand.modifySeedRice(SeedRice obj) {
        return false;
    }
    
    public void SeedRiceDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = SeedRice.findSeedRiceEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SeedRice' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SeedRice>();
        for (int i = 0; i < 10; i++) {
            SeedRice obj = getNewTransientSeedRice(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
