// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.spt.priceofriceservice.domain;

import com.spt.priceofriceservice.domain.SeedRiceDataOnDemand;
import com.spt.priceofriceservice.domain.TypeRice;
import com.spt.priceofriceservice.domain.TypeRiceDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect TypeRiceDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TypeRiceDataOnDemand: @Component;
    
    private Random TypeRiceDataOnDemand.rnd = new SecureRandom();
    
    private List<TypeRice> TypeRiceDataOnDemand.data;
    
    @Autowired
    SeedRiceDataOnDemand TypeRiceDataOnDemand.seedRiceDataOnDemand;
    
    public TypeRice TypeRiceDataOnDemand.getNewTransientTypeRice(int index) {
        TypeRice obj = new TypeRice();
        setDescription(obj, index);
        setTypeRiceCode(obj, index);
        setTypeRiceName(obj, index);
        return obj;
    }
    
    public void TypeRiceDataOnDemand.setDescription(TypeRice obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void TypeRiceDataOnDemand.setTypeRiceCode(TypeRice obj, int index) {
        String typeRiceCode = "typeRiceCode_" + index;
        obj.setTypeRiceCode(typeRiceCode);
    }
    
    public void TypeRiceDataOnDemand.setTypeRiceName(TypeRice obj, int index) {
        String typeRiceName = "typeRiceName_" + index;
        obj.setTypeRiceName(typeRiceName);
    }
    
    public TypeRice TypeRiceDataOnDemand.getSpecificTypeRice(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        TypeRice obj = data.get(index);
        Long id = obj.getId();
        return TypeRice.findTypeRice(id);
    }
    
    public TypeRice TypeRiceDataOnDemand.getRandomTypeRice() {
        init();
        TypeRice obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return TypeRice.findTypeRice(id);
    }
    
    public boolean TypeRiceDataOnDemand.modifyTypeRice(TypeRice obj) {
        return false;
    }
    
    public void TypeRiceDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = TypeRice.findTypeRiceEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'TypeRice' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<TypeRice>();
        for (int i = 0; i < 10; i++) {
            TypeRice obj = getNewTransientTypeRice(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
