// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.spt.priceofriceservice.domain;

import com.spt.priceofriceservice.domain.TypeRice;
import com.spt.priceofriceservice.domain.TypeRiceDataOnDemand;
import com.spt.priceofriceservice.domain.TypeRiceIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TypeRiceIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TypeRiceIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TypeRiceIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TypeRiceIntegrationTest: @Transactional;
    
    @Autowired
    TypeRiceDataOnDemand TypeRiceIntegrationTest.dod;
    
    @Test
    public void TypeRiceIntegrationTest.testCountTypeRices() {
        Assert.assertNotNull("Data on demand for 'TypeRice' failed to initialize correctly", dod.getRandomTypeRice());
        long count = TypeRice.countTypeRices();
        Assert.assertTrue("Counter for 'TypeRice' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TypeRiceIntegrationTest.testFindTypeRice() {
        TypeRice obj = dod.getRandomTypeRice();
        Assert.assertNotNull("Data on demand for 'TypeRice' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TypeRice' failed to provide an identifier", id);
        obj = TypeRice.findTypeRice(id);
        Assert.assertNotNull("Find method for 'TypeRice' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TypeRice' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TypeRiceIntegrationTest.testFindAllTypeRices() {
        Assert.assertNotNull("Data on demand for 'TypeRice' failed to initialize correctly", dod.getRandomTypeRice());
        long count = TypeRice.countTypeRices();
        Assert.assertTrue("Too expensive to perform a find all test for 'TypeRice', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TypeRice> result = TypeRice.findAllTypeRices();
        Assert.assertNotNull("Find all method for 'TypeRice' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TypeRice' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TypeRiceIntegrationTest.testFindTypeRiceEntries() {
        Assert.assertNotNull("Data on demand for 'TypeRice' failed to initialize correctly", dod.getRandomTypeRice());
        long count = TypeRice.countTypeRices();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TypeRice> result = TypeRice.findTypeRiceEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TypeRice' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TypeRice' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TypeRiceIntegrationTest.testFlush() {
        TypeRice obj = dod.getRandomTypeRice();
        Assert.assertNotNull("Data on demand for 'TypeRice' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TypeRice' failed to provide an identifier", id);
        obj = TypeRice.findTypeRice(id);
        Assert.assertNotNull("Find method for 'TypeRice' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTypeRice(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'TypeRice' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TypeRiceIntegrationTest.testMergeUpdate() {
        TypeRice obj = dod.getRandomTypeRice();
        Assert.assertNotNull("Data on demand for 'TypeRice' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TypeRice' failed to provide an identifier", id);
        obj = TypeRice.findTypeRice(id);
        boolean modified =  dod.modifyTypeRice(obj);
        Integer currentVersion = obj.getVersion();
        TypeRice merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'TypeRice' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TypeRiceIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'TypeRice' failed to initialize correctly", dod.getRandomTypeRice());
        TypeRice obj = dod.getNewTransientTypeRice(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TypeRice' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TypeRice' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'TypeRice' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TypeRiceIntegrationTest.testRemove() {
        TypeRice obj = dod.getRandomTypeRice();
        Assert.assertNotNull("Data on demand for 'TypeRice' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TypeRice' failed to provide an identifier", id);
        obj = TypeRice.findTypeRice(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'TypeRice' with identifier '" + id + "'", TypeRice.findTypeRice(id));
    }
    
}
