INSERT INTO "APP"."SEED_RICE" (SEED_RICE_CODE,SEED_RICE_NAME,VERSION) VALUES ('S001','ข้าวเหนียว',0);
INSERT INTO "APP"."SEED_RICE" (SEED_RICE_CODE,SEED_RICE_NAME,VERSION) VALUES ('S002','ข้าวนึ่ง',0);








INSERT INTO "APP"."TYPE_RICE" (DESCRIPTION,TYPE_RICE_CODE,TYPE_RICE_NAME,VERSION,SEED_RICE) VALUES ('สีดำ','T0001','อีสาน',0,1);









INSERT INTO "APP"."DATE_PRICE" (DATE_CODE,DATE_OF_PRICE,VERSION) VALUES ('20160301',{ts '2016-01-30 00:00:00.0'},0);









INSERT INTO "APP"."PRICE_PER_DAY" (PRICE,VERSION,DATE_PRICE,TYPE_RICE) VALUES (20.0,0,1,1);