// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.spt.priceofriceservice.domain;

import com.spt.priceofriceservice.domain.PricePerDay;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PricePerDay_Roo_Configurable {
    
    declare @type: PricePerDay: @Configurable;
    
}
